name: end to end pipline getways        #all devsecops pipline called here
on:
    push:
    workflow_dispatch:
jobs:
    code-quality-check:
        uses: ./.github/workflows/code-quality.yml
    dependency-scan:
        needs: code-quality-check
        uses: ./.github/workflows/dependency-scan.yml
    docker-file-scan:
        needs: [dependency-scan,code-quality-check]
        uses: ./.github/workflows/dockerfile-validate.yml
    docker-build-push:
        needs: [docker-file-scan,dependency-scan,code-quality-check]
        uses: ./.github/workflows/docker-build-push.yml
        secrets:
            DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    docker-image-scan:
        needs: [docker-build-push]
        uses: ./.github/workflows/Trivy-scan.yml
