name: Dockerfile validate
on:
    workflow_dispatch:
jobs:
    dockerfile-valid:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: dokerfile check
              uses: actions/checkout@v6
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
              